apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: development-rabbitmqcluster
spec:
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 1Gi
    limits:
      cpu: 350m
      memory: 1Gi
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 700
                  default_user= ***
                  default_pass = ***
                  default_user_tags.administrator = true
  service:
    type: LoadBalancer
